# -*- coding: utf-8 -*-
"""pitch&email.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qP7aArDQtFjtnKtmg9Ak312VkKZO7Pst
"""

!pip install --upgrade openai

import openai
import json

client = openai.OpenAI(
    api_key="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",
    project="proj_D20tqBrha8fjYOewDnxxHK4M"
)

"""#pitch content"""

def generate_pitch(startup_name, industry, product, traction, ask):
    prompt = f"""
You are a world-class startup storyteller.

Craft a 5-part investor pitch that feels like a compelling narrative — as if you were walking an investor through a journey.
It should flow like a short story, and build emotional + logical conviction.

Use the following 5 parts:

1. Problem — Start with a vivid story or insight that shows the pain clearly.
2. Solution — Introduce the product like a natural answer to the problem.
3. Market — Explain why this matters now, and how big the opportunity is.
4. Traction — Share real, credible proof that the team can execute.
5. Ask — Make the ask confidently, showing how the funds will drive growth.

Each part should return:
- a short story-style paragraph
- a confidence score between 0 and 1

Startup Name: {startup_name}
Industry: {industry}
Product: {product}
Current Traction: {traction}
Funding Ask: {ask}

Output only valid JSON in this format:
{{
  "problem": {{"text": "...", "confidence": 0.91}},
  "solution": {{"text": "...", "confidence": 0.89}},
  ...
}}
"""

    try:
        response = client.chat.completions.create(
            model="gpt-4",  # you can use gpt-4o or gpt-3.5-turbo
            messages=[{"role": "user", "content": prompt}],
            max_tokens=1000,
            temperature=0.85
        )
        return response.choices[0].message.content

    except openai.NotFoundError:
        print("trying other model...")
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}]
            )
            return response.choices[0].message.content
        except Exception as e:
            print(f"all failed: {e}")
            return None

    except Exception as e:
        print(f"API failed: {e}")
        return None

pitch = generate_pitch(
    startup_name="FlowPay",
    industry="B2B Fintech",
    product="A platform that automates supplier payments for enterprises",
    traction="Over $10M in monthly payment volume, 50+ enterprise clients",
    ask="$15M Series A for product & sales expansion"
)

if pitch:
    print(pitch)

    try:
        pitch_json = json.loads(pitch)
        print("\n✅ JSON parsed successfully!")
        for key, value in pitch_json.items():
            print(f"{key}: {value}")
    except:
        print("⚠️ The response is not valid JSON.")
else:
    print("❌ Pitch generation failed.")

"""#email"""

def generate_cold_email(pitch_json, investor_name="there", your_name="Your Name", startup_name="FlowPay", your_email="you@example.com"):
    try:
        problem = pitch_json["problem"]["text"]
        solution = pitch_json["solution"]["text"]
        traction = pitch_json["traction"]["text"]
        ask = pitch_json["ask"]["text"]

        traction_line = traction.split(".")[0] + "."
        ask_line = ask.split(".")[0] + "."

        email = f"""Subject: {startup_name} — Automating B2B payments at scale

Hi {investor_name},

I’m building {startup_name} — a B2B payments platform that helps enterprises automate supplier payments with speed and clarity.

{traction_line}
{ask_line}

I'd love to send over a short deck or hear your quick thoughts.

Best,
{your_name}
Founder, {startup_name}
{your_email}
"""
        return email

    except Exception as e:
        return f"❌ Failed to generate email: {e}"

cold_email = generate_cold_email(
    pitch_json=pitch_json,
    investor_name="Alex",
    your_name="Lily Zhang",
    your_email="lily@flowpay.com"
)

print(cold_email)

import re
import pandas as pd
import json

def contains_user_input(sentence, user_inputs):
    sentence_lower = sentence.lower()
    return any(user_input.lower() in sentence_lower for user_input in user_inputs if user_input)

def grade_sentence_by_content(text, user_inputs):
    vague_terms = [
        "some", "many", "various", "aim", "target", "expected", "$X", "X billion", "soon", "hope to",
        "a number of", "potential"
    ]
    red_flags = [
        "we believe", "we imagine", "we're redefining", "we aim to", "revolutionize",
        "game-changing", "disrupt", "visionary", "transforming", "we think"
    ]

    text_lower = text.lower()

    if contains_user_input(text, user_inputs):
        return "🟢 Green"
    elif any(term in text_lower for term in red_flags):
        return "🔴 Red"
    elif any(term in text_lower for term in vague_terms):
        return "🟠 Orange"
    else:
        return "🟠 Orange"


def split_and_grade_sentences_by_content(section_text, user_inputs):
    sentences = re.split(r'(?<=[.!?]) +', section_text.strip())
    graded = []
    for sentence in sentences:
        if sentence:
            grade = grade_sentence_by_content(sentence, user_inputs)
            graded.append({"Sentence": sentence, "Grade": grade})
    return graded


startup_name = "FlowPay"
industry = "B2B Fintech"
product = "A platform that automates supplier payments for enterprises"
traction = "Over $10M in monthly payment volume, 50+ enterprise clients"
ask = "$15M Series A for product & sales expansion"


user_inputs = [startup_name, industry, product, traction, ask]


pitch = generate_pitch(
    startup_name=startup_name,
    industry=industry,
    product=product,
    traction=traction,
    ask=ask
)


if pitch:
    try:
        pitch_json = json.loads(pitch)
        print("\n✅ JSON parsed successfully!")

        sentence_level_grades = []
        for section, data in pitch_json.items():
            sentence_level_grades.extend(split_and_grade_sentences_by_content(data["text"], user_inputs))

        df = pd.DataFrame(sentence_level_grades)
        print(df)

    except Exception as e:
        print("⚠️ The response is not valid JSON.")
        print(e)
else:
    print("❌ Pitch generation failed.")